version: "3.8"

services:
  api:
    build: .
    container_name: f1_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./f1_data_full_2025.db:/f1_data_full_2025.db
      - ./fastf1_cache:/fastf1_cache
