version: "3.8"

services:
  api:
    build: .
    container_name: f1_api
    ports:
      - "8000:8000"
    env_file:
      - .env  # Load environment variables from the .env file
    volumes:
      - ./f1_data.db:/app/f1_data_full_2025.db  # Persist SQLite database
      - ./fastf1_cache:/app/fastf1_cache  # Persist FastF1 cache
